name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            ext: .exe
          - os: ubuntu-latest
            ext: ""   # Linux: no extension
          - os: macos-13    # Intel macOS
            ext: ""         # macOS: no extension for binaries
          - os: macos-latest  # Apple Silicon
            ext: ""

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build CLI
      run: |
        pyinstaller --onefile --hidden-import encoder --hidden-import decoder --name imgfile-cli cli.py

    - name: Build GUI
      run: |
        pyinstaller --onefile --hidden-import encoder --hidden-import decoder --name imgfile-gui app.py

    # ✅ Cross-platform directory listing
    - name: List dist folder
      shell: bash
      run: |
        echo "Listing dist folder contents:"
        ls -l dist || dir dist

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: executables-${{ matrix.os }}
        path: |
          dist/imgfile-cli${{ matrix.ext }}
          dist/imgfile-gui${{ matrix.ext }}

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Download all build artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.0-build-${{ github.run_id }}
        name: Automatic Build ${{ github.run_id }}
        body: |
          Automatic release built from commit ${{ github.sha }}

          Includes executables for:
          - Windows (.exe)
          - Linux (no extension)
          - macOS Intel (no extension)
          - macOS Apple Silicon (no extension)
        files: ./artifacts/**/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
